language: node_js
node_js:
  - "10"
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - npm install
script:
  - npm run ts-test